/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package cw.jdbc;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;

public class App {
    public static void main(String[] args) throws SQLException {
        String dbUrl = "jdbc:h2:./test";
        Connection connection = DriverManager.getConnection(dbUrl);
        Statement statement = connection.createStatement();
        statement.executeUpdate("CREATE TABLE test_table (name VARCHAR(100))");
    }
}
